apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jlm7mbgjz-nodejs
  janus-idp.io/tekton: jlm7mbgjz-nodejs
  backstage.io/kubernetes-id: jlm7mbgjz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jlm7mbgjz-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
